src/components/credentialsForm.jsx

Remove the hard coded DB provider value in the create inventory api call

Remove the hard coded DB provider value in the create inventory api call

---

src/components/credentialsForm.jsx
src/components/dbaasImportPage.jsx
src/components/instanceListPage.jsx
src/components/instancesForm.jsx

Change inventories fetch api call to only fetch the newly created inventory

DBAAS-116 Change inventories fetch api call to only fetch the newly created inventory

---

src/components/_dbaas-import-view.css
src/components/credentialsForm.jsx
src/components/dbaasImportPage.jsx
src/components/instancesForm.jsx
src/components/vendorForm.jsx

Remove tabs use single page flow

DBAAS-120 Remove tabs use single page flow

---

src/components/_dbaas-import-view.css
src/components/credentialsForm.jsx
src/components/dbaasImportPage.jsx
src/components/vendorForm.jsx

add name field and change provider select to dropdown

DBAAS 121 add name field and change provider select to dropdown

---

src/components/_dbaas-import-view.css
src/components/dbaasImportPage.jsx
src/components/instanceListPage.jsx
src/components/instanceTable.jsx
src/components/instancesForm.jsx
src/components/providerAccountForm.jsx
src/const.ts

Sorry for combining 2 jiras
Jira: https://issues.redhat.com/browse/DBAAS-123
JIra: https://issues.redhat.com/browse/DBAAS-125

DBAAS-123 build result page

---

src/components/dbaasImportPage.jsx
src/components/providerAccountForm.jsx

- Fetch DBaaSProvider when the form loads.
- Use the info from DBaaSProvider to dynamically render credential fields.

DBAAS-110 Use dbaas provider cr to render credential fields

---

README.md
package.json
yarn.lock

upgrade dependencies

---

package-lock.json
yarn.lock

fix dep locks

---

src/components/instanceListPage.jsx
src/components/instancesForm.jsx

Modify the error page based on new UX design

DBAAS 143 Modify the error page based on new UX design

---

package-lock.json
package.json
src/components/instanceListPage.jsx
src/components/instanceTable.jsx
src/components/instancesForm.jsx
yarn.lock

add support for tenancy and the developer persona

---

src/components/instanceConnectionStatusTable.jsx
src/components/instanceListPage.jsx
src/components/instanceTable.jsx

Add connection status table to database instance list page

DBAAS-153: Add connection status table to database instance list page

---

src/components/instanceListPage.jsx
src/components/providerAccountForm.jsx

- If a tenant user attempts to create an inventory in an invalid tenant namespace, they will see this alert and will not be allowed to continue:
- ![Screen Shot 2021-09-22 at 1 33 42 PM](https://user-images.githubusercontent.com/11095048/134401722-7daa6e67-e68e-49f3-80e5-38dbd5300c99.png)
- if a user w/ no tenant privileges attempts to create an inventory in an invalid tenant namespace, they will see this alert and will not be allowed to continue:
- ![Screen Shot 2021-09-22 at 1 06 03 PM](https://user-images.githubusercontent.com/11095048/134397945-5ec2af97-bff7-447d-83c1-982b2b7b0a89.png)

add inventory namespace check

---

src/components/instanceListPage.jsx

[DBAAS-158] fix empty provider account dropdown

---

src/components/instanceTable.jsx

issue :  
https://issues.redhat.com/browse/DBAAS-159

Fiixed connection cr length by replacing instance id with current timestamp

---

src/components/instanceConnectionStatusTable.jsx
src/components/instanceListPage.jsx
src/components/instanceTable.jsx

Modify the connection status table based on the new design
Jira: [https://issues.redhat.com/browse/DBAAS-160](https://issues.redhat.com/browse/DBAAS-160)

Modify the connection status table based on the new design

---

.github/workflows/node.js.yml
Dockerfile
README.md
package.json
src/components/instanceTable.jsx

support versioned builds and reduce image size

---

Dockerfile
README.md
http-server.sh

fix image startup issue

---

Dockerfile
LICENSE

switch to ubi image

---

src/components/instanceListPage.jsx

depends on https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/40

[DBAAS-187] list connections from all accessible namespaces

---

package.json
src/components/providerAccountForm.jsx

required to support https://github.com/mongodb/mongodb-atlas-kubernetes/pull/389

set secret label based on provider type

---

console-extensions.json
src/components/instanceListPage.jsx
src/const.ts

Developer view (UI) support for CockroachDB Cloud operator - DBaaSConnection

Developer view (UI) support for CockroachDB Cloud operator - DBaaSCon

---

src/components/adminDashboard.jsx
src/components/instanceListPage.jsx

Update previous Alpha label to Service Preview in old workflows.

DBAAS-191: update release label

---

src/components/providerClusterProvisionPage.jsx

fix-pre-selected-provider-account-issue

fix-pre-selected-provider-account-issue

---

src/components/providerAccountForm.jsx

Remove default value for provider account name field and add validation
Jira: [https://issues.redhat.com/browse/DBAAS-308](https://issues.redhat.com/browse/DBAAS-308)

Remove default value for provider account name field and add validation

---

src/components/instanceListPage.jsx
src/components/instanceTable.jsx

Finished implementation of the new design for the Dev table

New design for the Dev table

---

src/components/instancesForm.jsx

JIra: [https://issues.redhat.com/browse/DBAAS-311](https://issues.redhat.com/browse/DBAAS-311)
In provider account creation flow stop the loop after the resource fetched successfully.

DBAAS 311 in provider account creation flow stop the loop after the resource fetched successfully

---

src/components/providerAccountForm.jsx

added the following validation
- Must consist of lower case alphanumeric characters, '-' or '.'
- Must start and end with an alphanumeric character
- No more than 63 characters in length

[DBAAS-310] add validation to the provider account name

---

src/components/instanceTable.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-319](https://issues.redhat.com/browse/DBAAS-319)

DBAAS-319: Update dev table columns

---

src/components/instanceListPage.jsx
src/components/providerAccountForm.jsx
src/const.ts

Jira: [https://issues.redhat.com/browse/DBAAS-321](https://issues.redhat.com/browse/DBAAS-321)
Jira: [https://issues.redhat.com/browse/DBAAS-322](https://issues.redhat.com/browse/DBAAS-322)

Add logo to the header of the dev dashboard and add helper text for provider account creation form

---

src/components/adminDashboard.jsx

update admin table defaults & view state

---

src/components/adminDashboard.jsx
src/components/providerClusterProvisionPage.jsx

Checking the allowsFreeTrial field to display the fields.

DBAAS-353 to show correct fields for Crunchy DB.

---

src/components/instanceListPage.jsx
src/components/instanceTable.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-363](https://issues.redhat.com/browse/DBAAS-363)

DBAAS-363 check inventory status when selected inventory is changed

---

src/components/adminDashboard.jsx

Checking instanceID, namespace and name
Code clean up.

DBAAS-352 grouping connections under Provider Acct vs Instance Name

---

src/components/providerClusterProvisionPage.jsx

Signed-off-by: Abdul Hameed <ahameed@redhat.com>

DBAAS-359 : fixed the namespace selection in inventory reference

---

src/components/adminDashboard.jsx

Showing 'No database instances' along with the Create Provider Account button.

DBAAS-366 Empty State implementation

---

src/components/providerClusterProvisionPage.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-362](https://issues.redhat.com/browse/DBAAS-362)

DBAAS-362 Show clear error msg when instance provisioning failed

---

src/components/adminDashboard.jsx
src/components/instanceTable.jsx

Admin table - added '--' If the DBAAS resources not bounded to any of the applications

DBAAS-373 Added '--' for the unbounded resources

---

src/components/providerAccountForm.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-367](https://issues.redhat.com/browse/DBAAS-367)

DBAAS-367 Reset credential fields when selected provider account change

---

src/components/instanceListPage.jsx

Disabling "Create Database Instance" button when there are no database resource available.

DBAAS-372 Disabling "Create Database Instance" button

---

src/components/instanceTable.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-376](https://issues.redhat.com/browse/DBAAS-376)

DBAAS-376: Fix the row selection issue for instance table

---

src/components/instanceListPage.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-366](https://issues.redhat.com/browse/DBAAS-366)

DBAAS 366 Show empty state when there is no provider account

---

src/utils.ts

Add error handling to the filterInventoriesByConnNS fuction to avoid the crash of the app

Add error handling to the filterInventoriesByConnNS fuction to avoid the crash of the app

---

src/components/instanceTable.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-385](https://issues.redhat.com/browse/DBAAS-385)
Fix column spacing issue for dev table and replace whitespace with dash to display empty value

DBAAS-385: Fix column spacing issue for dev table and replace whitespace with dash to display empty value

---

src/components/providerClusterProvisionPage.jsx

Added check for the status before displaying the error in the timeout scenario.

Timeout with the status of the instance being 'Ready'

---

src/components/instanceTable.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-385](https://issues.redhat.com/browse/DBAAS-385)

DBAAS-385: Fix white space issue for dev table

---

src/components/providerClusterProvisionPage.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-388](https://issues.redhat.com/browse/DBAAS-388)
Check inventory status when user select inventory in instance creation page.

DBAAS-388: Check inventory status when user select inventory in instance creation page.

---

package.json

increment version to 0.1.5

---

src/components/providerAccountForm.jsx

Added the await to the first fetch in order not to create an inventory without secret being in place.

Fix race condition

---

src/components/providerAccountForm.jsx

Cherry-pick for release branch: Fix race condition

---

console-extensions.json
package.json
webpack.config.ts
yarn.lock

Updates console SDK to make the plugin runnable on 4.10. But Im not entirely sure that the 0.0.5 version is a correct one.

Update console SDK to run on 4.10

---

src/components/_dbaas-import-view.css
src/components/instanceListFilter.tsx
src/components/instanceListPage.jsx
src/components/instancesForm.jsx

Cherry pick the change to release-0.14 branch

cherry-pick: Fix UI issues after upgrade console to 4.10

---

.github/workflows/node.js.yml
Dockerfile
package.json
tsconfig.json

cherry-pick: build fix

---

src/components/providerAccountForm.jsx

cherry-pick: change default creds label

---

package.json

increment minor version to 0.2.0

---

console-extensions.json
src/components/_dbaas-import-view.css
src/components/adminDashboard.jsx
src/components/dbaasImportPage.jsx
src/components/providerAccountForm.jsx

Modified the provider account import page based on new UI design
Jira: [https://issues.redhat.com/browse/DBAAS-510](https://issues.redhat.com/browse/DBAAS-510)

DBAAS-510: Modified the provider account import page based on new UI design

---

console-extensions.json
src/components/_dbaas-import-view.css
src/components/adminDashboard.jsx
src/components/dbaasImportPage.jsx
src/components/providerAccountForm.jsx

Same PR with [109](https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/109) but against release-0.1.5 branch
Jira: [https://issues.redhat.com/browse/DBAAS-510](https://issues.redhat.com/browse/DBAAS-510)

cherry-pick: Modified the provider account import page based on new UI design

---

src/components/adminConnectionsTable.jsx
src/components/adminDashboard.jsx

DBAAS-527 - Empty state verbiage change for the admin dashboard

---

src/components/providerAccountForm.jsx
src/const.ts

Modified the provider account import page based on the UX design.

DBAAS-528: Provider Account Import Page changes

---

console-extensions.json
src/catalog/providers/useDBaaSCatalog.tsx
src/components/_dbaas-import-view.css
src/components/adminConnectionsTable.jsx
src/components/instanceListPage.jsx
src/components/instanceTable.jsx
src/const.ts

Jira: [https://issues.redhat.com/browse/DBAAS-529](https://issues.redhat.com/browse/DBAAS-529)
Modified the developer dashboard based on the new UXD design
- Change "Connect" button to "Add to Topology" button
- Change page title, and field names
- Change the position of the "Create New Database Instance" button.
- Make the "Add to Topology" button and the "Cancel" button always sticky to the bottom of the window.
- Add a modal to show the instructions to use Topology view.
- Hide the left side catalog list for now

DBAAS-529 Modified the developer dashboard based on the new UXD design

---

console-extensions.json
src/catalog/providers/useDBaaSCatalog.tsx
src/components/_dbaas-import-view.css
src/components/adminConnectionsTable.jsx
src/components/instanceListPage.jsx
src/components/instanceTable.jsx
src/const.ts

Same PR with [121](https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/121), but for release-0.1.5-4.9 branch

DBAAS-529-for-release-0.1.5-4.9

---

src/components/providerClusterProvisionPage.jsx

Jira: https://issues.redhat.com/browse/DBAAS-530
Modified the create instance page based on the new UXD design.

DBAAS-530: instance page changes

---

src/components/providerClusterProvisionPage.jsx

Modified the create instance page based on the new UXD design, Added DB Provider back into the screen

DBAAS-530: Modified the create instance page based on the new UXD 

---

package.json

This reverts commit 38e18d022103b5f2a8326e7499c39dcfd1586edb.

Revert "increment minor version to 0.2.0"

---

src/components/instanceListPage.jsx
src/components/providerAccountForm.jsx
src/const.ts

Jira: [https://issues.redhat.com/browse/DBAAS-540](https://issues.redhat.com/browse/DBAAS-540)

DBAAS-540: Update UI with production doc links

---

src/components/instanceListPage.jsx
src/components/providerAccountForm.jsx
src/const.ts

Same with [128](https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/128) but for release-0.1.5-4.9 branch

DBAAS-540 for release-0.1.5-4.9

---

src/components/providerClusterProvisionPage.jsx

Cherry pick for 0.1.5-4.9
Fixed the message displayed when failing to create a database instance according to mock up

DBAAS-575: Cherry pick for 0.1.5-4.9

---

src/components/providerClusterProvisionPage.jsx

Cherry pick for 0.1.5
Fixed the message displayed when failing to create a database instance according to mock up

DBAAS-575: Cherry pick for 0.1.5

---

src/components/providerAccountForm.jsx

Cherry picking for 0.1.5
Fixed the "Database Provider" drop down to load at the same time as the 'Name' field.

DBAAS-559: Cherry picking for 0.1.5

---

src/components/providerAccountForm.jsx

Cherry picking for 0.1.5-4.9
Fixed the "Database Provider" drop down to load at the sam…e time as the 'Name' field.

DBAAS-559: Cherry picking for 0.1.5-4.9

---

src/components/adminDashboard.jsx
src/components/instanceListPage.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-592](https://issues.redhat.com/browse/DBAAS-592)
Fixed the page refresh issue when press enter key

DBAAS-592: Fixed the page refresh issue when press enter key

---

src/components/adminDashboard.jsx
src/components/instanceListPage.jsx

Same with [https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/140](https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/140) but for release-0.1.5 branch

DBAAS-592 for release 0.1.5 branch

---

src/components/adminDashboard.jsx
src/components/instanceListPage.jsx

Same with [https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/140](https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/140) but for release-0.1.5 branch

DBAAS-592 for release 0.1.5-4.9 branch

---

src/components/providerClusterProvisionPage.jsx

cherry-pick of PR #143 [DBAAS-597]

cherry-pick of PR #143 [DBAAS-597] to release-0.1.5

---

src/components/providerClusterProvisionPage.jsx

cherry-pick of PR #143 [DBAAS-597]

cherry-pick of PR #143 [DBAAS-597] to release-0.1.5-4.9

---

src/components/adminConnectionsTable.jsx
src/components/adminDashboard.jsx

Cherry picking for 0.1.5-4.9
Fixed the message for the tooltip displayed in case of the Connection failure.

DBAAS-599: Cherry picking for 0.1.5-4.9

---

src/components/adminConnectionsTable.jsx
src/components/adminDashboard.jsx

Cherry picking for 0.1.5
Fixed the message for the tooltip displayed in case of the Connection failure.

DBAAS-599: Cherry picking for 0.1.5

---

src/components/_dbaas-import-view.css
src/components/instanceTable.jsx

Fixed the bottom sticky section displaying issue for developer dashboard
Jira: [https://issues.redhat.com/browse/DBAAS-618](https://issues.redhat.com/browse/DBAAS-618)

DBAAS-618: Fixed the bottom sticky section displaying issue for developer dashboard

---

src/components/_dbaas-import-view.css
src/components/instanceTable.jsx

DBAAS 618 for release 0.1.5

---

src/components/_dbaas-import-view.css
src/components/instanceTable.jsx

DBAAS 618 for release-0.1.5-4.9

DBAAS 618 for release-0.1.5-4.9

---

src/components/adminDashboard.jsx
src/components/instanceListPage.jsx
src/components/providerAccountForm.jsx
src/components/providerClusterProvisionPage.jsx
src/const.ts

RDS instance form fields

---

src/components/adminDashboard.jsx
src/components/instanceListPage.jsx

fix broken provision link

---

src/components/adminDashboard.jsx

cherry-pick: fix admin dashboard inventory list

---

src/components/providerAccountForm.jsx

Jira: [Modify the provider account import form to fix the validation issue](Modify the provider account import form to fix the validation issue)

Skip validation for optional fields in import provider account form

---

src/components/_dbaas-import-view.css
src/components/providerClusterProvisionPage.jsx

Cherry picking for 0.2.0
Create DB Instance Warning and Contextual Help for Amazaon RDS

DBAAS-737: Cherry picking for 0.2.0

---

src/components/instancesForm.jsx
src/components/providerClusterProvisionPage.jsx
src/const.ts

DBAAS-742 for release-0.2.0

---

src/components/instancesForm.jsx

DBAAS-750 for release 0.2.0 4.9

DBAAS-750 for release 0.2.0 4.9

---

src/components/instancesForm.jsx

DBAAS-750 for release-0.2.0

---

console-extensions.json
src/components/_dbaas-import-view.css
src/components/providerAccountForm.jsx

DBAAS 755 for release 0.2.0 4.9

DBAAS 755 for release 0.2.0 4.9

---

console-extensions.json

Jira: [https://issues.redhat.com/browse/DBAAS-761](https://issues.redhat.com/browse/DBAAS-761)

DBAAS-761: Changed text for cloud hosted database card

---

console-extensions.json

DBAAS-761 for release-0.2.0-4.9

DBAAS-761 for release-0.2.0-4.9

---

package.json

0.3.0 and build command enhancements

---

src/components/_dbaas-import-view.css
src/components/instanceListFilter.tsx

Jira: [https://issues.redhat.com/browse/DBAAS-792](https://issues.redhat.com/browse/DBAAS-792)

DBAAS-792: Fixed the search bar layout issue

---

.yarnrc

[DBAAS-770] stop node dependency upgrades during builds

---

src/components/_dbaas-import-view.css
src/components/providerAccountForm.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-850](https://issues.redhat.com/browse/DBAAS-850)

DBAAS-850: Modified the provider account form for RDS

---

Dockerfile

Updated Dockerfile nodejs from version 14 to version 16

Update to nodejs-16

---

.github/workflows/node.js.yml

upgrade tested node versions

---

src/components/instancesForm.jsx

Jira: https://issues.redhat.com/browse/DBAAS-920
Fixed the Close button While importing provider account from Developer view to point to Developer -> +Add page.

DBAAS-920 - Close button

---

src/components/instanceListPage.jsx
src/components/instancesForm.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-929](https://issues.redhat.com/browse/DBAAS-929)
Users click the Close button or Cancel button, they are redirected to the previous view.
This should also fix the issue for [https://issues.redhat.com/browse/DBAAS-920](https://issues.redhat.com/browse/DBAAS-920)

DBAAS-929: Fixed the close button issue in developer view

---

.github/workflows/push.yml
package.json

this will push an image to quay.io in the following format -
```bash
quay.io/ecosystem-appeng/dbaas-dynamic-plugin-dev:<package-version>-<short git sha>
```
A test image was pushed by this workflow to my personal quay repo - 
`quay.io/tchughesiv/dbaas-dynamic-plugin-dev:0.3.0-d088522`

push a dev build with each merge

---

.github/workflows/push.yml
org-secret.js
package.json

update org secret with latest dev image url

---

.github/workflows/push.yml
dev-img-secret.js

secret related changes

---

.github/workflows/push.yml
dev-img-secret.js

change token name

---

package.json

increment version to 0.4.0

---

console-extensions.json
dev-img-secret.js
src/catalog/const.ts
src/components/adminDashboard.jsx
src/components/dbaasImportPage.jsx
src/components/instanceListPage.jsx
src/components/instanceTable.jsx
src/components/instancesForm.jsx
src/components/providerAccountForm.jsx
src/components/providerClusterProvisionPage.jsx
src/const.ts
src/models/dbaas.ts
src/utils.ts

depends on https://github.com/RHEcosystemAppEng/dbaas-operator/pull/296

[DBAAS-889] v1beta1 api changes

---

console-extensions.json
src/components/adminDashboard.jsx
src/utils.ts

Fixes 404 error for "All Projects" selection. Also, allows user to switch between namespaces on Database Access page.
For a new "non-admin" user, with no projects created yet... the view will be the following, until they create their first project. once a project is added by the user, their view will resemble the first screenshot above.

[DBAAS-306] fix `all-namespaces` db access view

---

src/components/adminDashboard.jsx

[DBAAS-1162] fix inventory table delay

---

src/components/adminDashboard.jsx

[DBAAS-1162] fixes

---

src/components/adminDashboard.jsx
src/components/providerClusterProvisionPage.jsx

DBAAS-860-UI: changes for full provisioning for Instance Creation page for all the providers.
jira: https://issues.redhat.com/browse/DBAAS-860
mockup: https://marvelapp.com/prototype/j310e34/screen/89805016

DBAAS-860-UI: Full provisioning

---

src/components/adminConnectionsTable.jsx
src/components/adminDashboard.jsx
src/components/instanceConnectionStatusTable.jsx
src/components/instanceListPage.jsx
src/components/instanceTable.jsx
src/components/instancesForm.jsx
src/components/providerClusterProvisionPage.jsx

related to https://github.com/RHEcosystemAppEng/dbaas-operator/pull/323

[DBAAS-981] update api to support cluster

---

src/components/providerClusterProvisionPage.jsx

Setting the defaults for the provider was missing when coming from the DEV perspective.
Jira: https://issues.redhat.com/browse/DBAAS-1188

DBAAS-1188: UX not loaded from the developer perspective

---

src/components/adminDashboard.jsx

[DBAAS-1162] resolve delay on initial admin dash landing

---

src/components/instanceTable.jsx

Jira: [https://issues.redhat.com/browse/DBAAS-1194](https://issues.redhat.com/browse/DBAAS-1194)

DBAAS-1194: Fix the redirection issue for cancel button on instance table

---

src/components/adminDashboard.jsx

[DBAAS-1162] fix for normal user view - no projects

---

src/components/instanceListPage.jsx
src/utils.ts

[DBAAS-1112] fix 'Create New Database Instance' button, disabled when necessary

---

src/components/providerClusterProvisionPage.jsx

Fixed 'DB instance class' field to show values depending on what databaseType was chosen.
Jira: https://issues.redhat.com/browse/DBAAS-1201

DBAAS-1201: Fixed 'DB instance class' field to show correct values

---

src/components/instanceTable.jsx

DBAAS-1196: Added 'databaseServiceType'
Jira: https://issues.redhat.com/browse/DBAAS-1196

DBAAS-1196: Added 'databaseServiceType'

---

console-extensions.json
package.json
src/components/adminDashboard.jsx
src/components/instanceListPage.jsx
src/components/providerClusterProvisionPage.jsx

[DBAAS-1254] Rebrand RHODA to OpenShift Database Access

---

src/components/providerClusterProvisionPage.jsx

Instance creation was failing when coming from Dev view because provider defaults were not set.
Jira: https://issues.redhat.com/browse/DBAAS-1226

DBAAS-1226: Instance creation was failing when coming from Dev view

---

src/components/providerClusterProvisionPage.jsx

relates to https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/237

DBAAS-1272 - fix provisioning redirect
